// Code generated by protoc-gen-go. DO NOT EDIT.
// source: launch.proto

package login

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type C2SLaunch struct {
	//
	// index begin from 1, and increase every re-launch.
	// hashkey(a) transfer a to 8 byte key.
	//
	// etoken = base64(token)+"@"+base64(subid)+":"+base64(index)
	// hmac = base64(hmac64_md5(hashkey(etoken), secret))
	// signature = etoken+":"+hmac
	Signature        *string `protobuf:"bytes,1,req,name=signature" json:"signature,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2SLaunch) Reset()                    { *m = C2SLaunch{} }
func (m *C2SLaunch) String() string            { return proto.CompactTextString(m) }
func (*C2SLaunch) ProtoMessage()               {}
func (*C2SLaunch) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *C2SLaunch) GetSignature() string {
	if m != nil && m.Signature != nil {
		return *m.Signature
	}
	return ""
}

type S2CLaunch struct {
	Code             *int32               `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Player           *S2CLaunchPlayerInfo `protobuf:"bytes,2,opt,name=player" json:"player,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *S2CLaunch) Reset()                    { *m = S2CLaunch{} }
func (m *S2CLaunch) String() string            { return proto.CompactTextString(m) }
func (*S2CLaunch) ProtoMessage()               {}
func (*S2CLaunch) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *S2CLaunch) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *S2CLaunch) GetPlayer() *S2CLaunchPlayerInfo {
	if m != nil {
		return m.Player
	}
	return nil
}

type S2CLaunchPlayerInfo struct {
	Id               *uint64 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	Level            *uint32 `protobuf:"varint,3,opt,name=level" json:"level,omitempty"`
	Exp              *uint32 `protobuf:"varint,4,opt,name=exp" json:"exp,omitempty"`
	Gold             *uint32 `protobuf:"varint,5,opt,name=gold" json:"gold,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *S2CLaunchPlayerInfo) Reset()                    { *m = S2CLaunchPlayerInfo{} }
func (m *S2CLaunchPlayerInfo) String() string            { return proto.CompactTextString(m) }
func (*S2CLaunchPlayerInfo) ProtoMessage()               {}
func (*S2CLaunchPlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1, 0} }

func (m *S2CLaunchPlayerInfo) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *S2CLaunchPlayerInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *S2CLaunchPlayerInfo) GetLevel() uint32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *S2CLaunchPlayerInfo) GetExp() uint32 {
	if m != nil && m.Exp != nil {
		return *m.Exp
	}
	return 0
}

func (m *S2CLaunchPlayerInfo) GetGold() uint32 {
	if m != nil && m.Gold != nil {
		return *m.Gold
	}
	return 0
}

func init() {
	proto.RegisterType((*C2SLaunch)(nil), "login.c2s_launch")
	proto.RegisterType((*S2CLaunch)(nil), "login.s2c_launch")
	proto.RegisterType((*S2CLaunchPlayerInfo)(nil), "login.s2c_launch.player_info")
}

func init() { proto.RegisterFile("launch.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x69, 0xb7, 0x15, 0x76, 0xda, 0x3d, 0x98, 0x53, 0x10, 0xc4, 0xb2, 0xa7, 0x5e, 0x4c,
	0xa5, 0x8f, 0xe0, 0xd9, 0x8b, 0xe0, 0xc9, 0xcb, 0x12, 0x93, 0x31, 0x0d, 0x64, 0x33, 0xa5, 0x49,
	0x17, 0xf7, 0x5d, 0x7c, 0x58, 0x49, 0x8a, 0xe8, 0xf1, 0xe7, 0x9b, 0xf9, 0xe6, 0x1f, 0x68, 0x9d,
	0x5c, 0xbd, 0x9a, 0xc4, 0xbc, 0x50, 0x24, 0x56, 0x3b, 0x32, 0xd6, 0x1f, 0x1f, 0x00, 0xd4, 0x18,
	0x4e, 0x1b, 0x62, 0xb7, 0xb0, 0x0f, 0xd6, 0x78, 0x19, 0xd7, 0x05, 0x79, 0xd1, 0x95, 0xfd, 0xfe,
	0xf8, 0x5d, 0x00, 0x84, 0x51, 0xfd, 0x4e, 0xb4, 0x50, 0x29, 0xd2, 0x1b, 0xac, 0xd9, 0x23, 0xdc,
	0xcc, 0x4e, 0x5e, 0x71, 0xe1, 0x65, 0x57, 0xf4, 0xcd, 0x78, 0x2f, 0xb2, 0x55, 0xfc, 0x2d, 0x88,
	0x8d, 0x9f, 0xac, 0xff, 0xa4, 0xbb, 0x57, 0x68, 0xfe, 0x45, 0x06, 0x50, 0x5a, 0x9d, 0x4d, 0x55,
	0xf2, 0x7a, 0x79, 0x46, 0x5e, 0xa6, 0xa3, 0xec, 0x00, 0xb5, 0xc3, 0x0b, 0x3a, 0xbe, 0xeb, 0x8a,
	0xfe, 0xc0, 0x1a, 0xd8, 0xe1, 0xd7, 0xcc, 0xab, 0x1c, 0x5a, 0xa8, 0x0c, 0x39, 0xcd, 0xeb, 0x94,
	0x9e, 0x9f, 0xde, 0x85, 0xb1, 0x71, 0x5a, 0x3f, 0x84, 0xa2, 0xf3, 0xa0, 0xe5, 0xc5, 0xea, 0x09,
	0xfd, 0x72, 0x35, 0x92, 0x86, 0x97, 0xd4, 0xe5, 0x0d, 0x43, 0x1c, 0xf2, 0xcb, 0x43, 0xee, 0xf6,
	0x13, 0x00, 0x00, 0xff, 0xff, 0x2b, 0x2d, 0x60, 0xed, 0x07, 0x01, 0x00, 0x00,
}
