// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package login

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type C2SLogin struct {
	Platformid       *uint32 `protobuf:"varint,1,req,name=platformid" json:"platformid,omitempty"`
	Openid           *string `protobuf:"bytes,2,req,name=openid" json:"openid,omitempty"`
	Unionid          *string `protobuf:"bytes,3,opt,name=unionid" json:"unionid,omitempty"`
	Nickname         *string `protobuf:"bytes,4,opt,name=nickname" json:"nickname,omitempty"`
	Headimgurl       *string `protobuf:"bytes,5,opt,name=headimgurl" json:"headimgurl,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2SLogin) Reset()                    { *m = C2SLogin{} }
func (m *C2SLogin) String() string            { return proto.CompactTextString(m) }
func (*C2SLogin) ProtoMessage()               {}
func (*C2SLogin) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *C2SLogin) GetPlatformid() uint32 {
	if m != nil && m.Platformid != nil {
		return *m.Platformid
	}
	return 0
}

func (m *C2SLogin) GetOpenid() string {
	if m != nil && m.Openid != nil {
		return *m.Openid
	}
	return ""
}

func (m *C2SLogin) GetUnionid() string {
	if m != nil && m.Unionid != nil {
		return *m.Unionid
	}
	return ""
}

func (m *C2SLogin) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *C2SLogin) GetHeadimgurl() string {
	if m != nil && m.Headimgurl != nil {
		return *m.Headimgurl
	}
	return ""
}

type S2CLogin struct {
	Code             *int32          `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Info             *S2CLoginResult `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *S2CLogin) Reset()                    { *m = S2CLogin{} }
func (m *S2CLogin) String() string            { return proto.CompactTextString(m) }
func (*S2CLogin) ProtoMessage()               {}
func (*S2CLogin) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *S2CLogin) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *S2CLogin) GetInfo() *S2CLoginResult {
	if m != nil {
		return m.Info
	}
	return nil
}

type S2CLoginResult struct {
	Subid            *string `protobuf:"bytes,1,req,name=subid" json:"subid,omitempty"`
	ServerAddr       *string `protobuf:"bytes,2,req,name=server_addr" json:"server_addr,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *S2CLoginResult) Reset()                    { *m = S2CLoginResult{} }
func (m *S2CLoginResult) String() string            { return proto.CompactTextString(m) }
func (*S2CLoginResult) ProtoMessage()               {}
func (*S2CLoginResult) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1, 0} }

func (m *S2CLoginResult) GetSubid() string {
	if m != nil && m.Subid != nil {
		return *m.Subid
	}
	return ""
}

func (m *S2CLoginResult) GetServerAddr() string {
	if m != nil && m.ServerAddr != nil {
		return *m.ServerAddr
	}
	return ""
}

func init() {
	proto.RegisterType((*C2SLogin)(nil), "protocol.c2s_login")
	proto.RegisterType((*S2CLogin)(nil), "protocol.s2c_login")
	proto.RegisterType((*S2CLoginResult)(nil), "protocol.s2c_login.result")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x40, 0x95, 0x90, 0x94, 0xe6, 0x42, 0x01, 0x1d, 0x4b, 0xd4, 0x29, 0xea, 0x94, 0x01, 0x39,
	0x28, 0x3f, 0x81, 0x99, 0x91, 0x89, 0xa5, 0x72, 0x6d, 0x27, 0xb1, 0x48, 0x7c, 0xc1, 0x1f, 0x95,
	0xf8, 0xf7, 0x28, 0x6e, 0xe9, 0x64, 0xeb, 0x9d, 0xee, 0xde, 0x83, 0x72, 0xa2, 0x41, 0x1b, 0xb6,
	0x58, 0xf2, 0x84, 0xdb, 0xf8, 0x08, 0x9a, 0x0e, 0x3d, 0x14, 0xa2, 0x73, 0xc7, 0x38, 0x44, 0x04,
	0x58, 0x26, 0xee, 0x7b, 0xb2, 0xb3, 0x96, 0x55, 0x52, 0xa7, 0xcd, 0x0e, 0x1f, 0x61, 0x43, 0x8b,
	0x32, 0x5a, 0x56, 0x69, 0x9d, 0x36, 0x05, 0x3e, 0xc1, 0x7d, 0x30, 0x9a, 0x56, 0x70, 0x57, 0x27,
	0x4d, 0x81, 0xcf, 0xb0, 0x35, 0x5a, 0x7c, 0x1b, 0x3e, 0xab, 0x2a, 0x8b, 0x04, 0x01, 0x46, 0xc5,
	0xa5, 0x9e, 0x87, 0x60, 0xa7, 0x2a, 0x5f, 0xd9, 0xe1, 0x07, 0x0a, 0xd7, 0x89, 0xab, 0xe7, 0x01,
	0x32, 0x41, 0x52, 0x45, 0x43, 0x8e, 0x0d, 0x64, 0xda, 0xf4, 0x54, 0xa5, 0x75, 0xd2, 0x94, 0xdd,
	0x9e, 0xfd, 0xb7, 0xb1, 0xdb, 0x02, 0xb3, 0xca, 0x85, 0xc9, 0xef, 0x5f, 0x61, 0x73, 0xf9, 0xe1,
	0x0e, 0x72, 0x17, 0x4e, 0xd7, 0xc8, 0x02, 0x5f, 0xa0, 0x74, 0xca, 0x9e, 0x95, 0x3d, 0x72, 0x29,
	0xed, 0xa5, 0xf4, 0xfd, 0xed, 0x8b, 0x0d, 0xda, 0x8f, 0xe1, 0xc4, 0x04, 0xcd, 0xad, 0xe4, 0x67,
	0x2d, 0x47, 0x65, 0xec, 0xef, 0xc0, 0xa9, 0xfd, 0x58, 0xcf, 0x7e, 0x2a, 0xe7, 0xdb, 0x68, 0x6b,
	0xa3, 0xe6, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x28, 0x3c, 0x30, 0x10, 0x24, 0x01, 0x00, 0x00,
}
