// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package login

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type C2SLogin struct {
	Token            *string `protobuf:"bytes,1,req,name=token" json:"token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2SLogin) Reset()                    { *m = C2SLogin{} }
func (m *C2SLogin) String() string            { return proto.CompactTextString(m) }
func (*C2SLogin) ProtoMessage()               {}
func (*C2SLogin) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *C2SLogin) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

type S2CLogin struct {
	Code             *int32          `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Info             *S2CLoginResult `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *S2CLogin) Reset()                    { *m = S2CLogin{} }
func (m *S2CLogin) String() string            { return proto.CompactTextString(m) }
func (*S2CLogin) ProtoMessage()               {}
func (*S2CLogin) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *S2CLogin) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *S2CLogin) GetInfo() *S2CLoginResult {
	if m != nil {
		return m.Info
	}
	return nil
}

type S2CLoginResult struct {
	Subid            *string `protobuf:"bytes,1,req,name=subid" json:"subid,omitempty"`
	ServerAddr       *string `protobuf:"bytes,2,req,name=server_addr" json:"server_addr,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *S2CLoginResult) Reset()                    { *m = S2CLoginResult{} }
func (m *S2CLoginResult) String() string            { return proto.CompactTextString(m) }
func (*S2CLoginResult) ProtoMessage()               {}
func (*S2CLoginResult) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1, 0} }

func (m *S2CLoginResult) GetSubid() string {
	if m != nil && m.Subid != nil {
		return *m.Subid
	}
	return ""
}

func (m *S2CLoginResult) GetServerAddr() string {
	if m != nil && m.ServerAddr != nil {
		return *m.ServerAddr
	}
	return ""
}

func init() {
	proto.RegisterType((*C2SLogin)(nil), "login.c2s_login")
	proto.RegisterType((*S2CLogin)(nil), "login.s2c_login")
	proto.RegisterType((*S2CLoginResult)(nil), "login.s2c_login.result")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0xb1, 0x0e, 0x82, 0x30,
	0x10, 0x86, 0x03, 0x01, 0x13, 0x0e, 0x5d, 0xea, 0x20, 0x61, 0x22, 0x24, 0x26, 0x0c, 0xa6, 0x35,
	0x3c, 0x82, 0xb3, 0xa3, 0x93, 0x0b, 0x81, 0xb6, 0x42, 0x23, 0xf6, 0x4c, 0x5b, 0x48, 0x7c, 0x7b,
	0x43, 0x31, 0x6e, 0xf7, 0xdf, 0x77, 0xf9, 0xee, 0x87, 0x74, 0xc4, 0x5e, 0x69, 0xfa, 0x36, 0xe8,
	0x90, 0xc4, 0x3e, 0x94, 0x39, 0x24, 0xbc, 0xb6, 0x8d, 0x0f, 0x64, 0x07, 0xb1, 0xc3, 0xa7, 0xd4,
	0x59, 0x50, 0x84, 0x55, 0x52, 0x6a, 0x48, 0x6c, 0xcd, 0x7f, 0x6c, 0x0b, 0x11, 0x47, 0x21, 0x3d,
	0x8a, 0xc9, 0x11, 0x22, 0xa5, 0x1f, 0x98, 0x85, 0x45, 0x50, 0xa5, 0xf5, 0x81, 0xae, 0xe6, 0xff,
	0x35, 0x35, 0xd2, 0x4e, 0xa3, 0xcb, 0x4f, 0xb0, 0x59, 0xa7, 0x45, 0x6d, 0xa7, 0x4e, 0x89, 0x55,
	0x4d, 0xf6, 0x90, 0x5a, 0x69, 0x66, 0x69, 0x9a, 0x56, 0x08, 0x93, 0x85, 0xcb, 0xf2, 0x72, 0xbe,
	0xd3, 0x5e, 0xb9, 0x61, 0xea, 0x28, 0xc7, 0x17, 0x13, 0xed, 0xac, 0xc4, 0x20, 0xb5, 0xf9, 0xf4,
	0x2d, 0xb2, 0xeb, 0xa2, 0xbd, 0x49, 0xeb, 0x98, 0xaf, 0xcf, 0xfc, 0x9b, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x41, 0x83, 0xfa, 0xe6, 0xd2, 0x00, 0x00, 0x00,
}
