// Code generated by protoc-gen-go. DO NOT EDIT.
// source: echo.proto

/*
Package player is a generated protocol buffer package.

It is generated from these files:
	echo.proto
	logout.proto

It has these top-level messages:
	C2SEcho
	S2CEcho
	C2SLogout
	S2CLogout
*/
package player

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type C2SEcho struct {
	Msg              *string `protobuf:"bytes,1,req,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2SEcho) Reset()                    { *m = C2SEcho{} }
func (m *C2SEcho) String() string            { return proto.CompactTextString(m) }
func (*C2SEcho) ProtoMessage()               {}
func (*C2SEcho) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *C2SEcho) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

type S2CEcho struct {
	Msg              *string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *S2CEcho) Reset()                    { *m = S2CEcho{} }
func (m *S2CEcho) String() string            { return proto.CompactTextString(m) }
func (*S2CEcho) ProtoMessage()               {}
func (*S2CEcho) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *S2CEcho) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*C2SEcho)(nil), "player.c2s_echo")
	proto.RegisterType((*S2CEcho)(nil), "player.s2c_echo")
}

func init() { proto.RegisterFile("echo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4d, 0xce, 0xc8,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0xc8, 0x49, 0xac, 0x4c, 0x2d, 0x52, 0x12,
	0xe7, 0xe2, 0x48, 0x36, 0x2a, 0x8e, 0x07, 0xc9, 0x08, 0x71, 0x73, 0x31, 0xe7, 0x16, 0xa7, 0x4b,
	0x30, 0x2a, 0x30, 0x69, 0x70, 0x82, 0x24, 0x8a, 0x8d, 0x92, 0xd1, 0x24, 0x18, 0x35, 0x38, 0x9d,
	0x0c, 0xa3, 0xf4, 0xd3, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x53, 0x12,
	0xcb, 0x32, 0x53, 0x32, 0x52, 0xf3, 0x8a, 0x2a, 0xd3, 0x13, 0xf3, 0xf5, 0x7d, 0xf2, 0xd3, 0x33,
	0xf3, 0x42, 0x52, 0x8b, 0x4b, 0xf4, 0xc1, 0xb6, 0xe8, 0x43, 0x2c, 0x01, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x85, 0x77, 0x4b, 0x7b, 0x79, 0x00, 0x00, 0x00,
}
