// Code generated by protoc-gen-go. DO NOT EDIT.
// source: battle_init.proto

package battle

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type S2CBattleInit struct {
	BattleId         *uint32                          `protobuf:"varint,1,req,name=battle_id" json:"battle_id,omitempty"`
	Random           *uint32                          `protobuf:"varint,2,req,name=random" json:"random,omitempty"`
	ServerAddr       *string                          `protobuf:"bytes,3,req,name=server_addr" json:"server_addr,omitempty"`
	TeamAmount       *uint32                          `protobuf:"varint,4,req,name=team_amount" json:"team_amount,omitempty"`
	PlayersInfo      []*S2CBattleInitBattlePlayerInfo `protobuf:"bytes,5,rep,name=players_info" json:"players_info,omitempty"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (m *S2CBattleInit) Reset()                    { *m = S2CBattleInit{} }
func (m *S2CBattleInit) String() string            { return proto.CompactTextString(m) }
func (*S2CBattleInit) ProtoMessage()               {}
func (*S2CBattleInit) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *S2CBattleInit) GetBattleId() uint32 {
	if m != nil && m.BattleId != nil {
		return *m.BattleId
	}
	return 0
}

func (m *S2CBattleInit) GetRandom() uint32 {
	if m != nil && m.Random != nil {
		return *m.Random
	}
	return 0
}

func (m *S2CBattleInit) GetServerAddr() string {
	if m != nil && m.ServerAddr != nil {
		return *m.ServerAddr
	}
	return ""
}

func (m *S2CBattleInit) GetTeamAmount() uint32 {
	if m != nil && m.TeamAmount != nil {
		return *m.TeamAmount
	}
	return 0
}

func (m *S2CBattleInit) GetPlayersInfo() []*S2CBattleInitBattlePlayerInfo {
	if m != nil {
		return m.PlayersInfo
	}
	return nil
}

type S2CBattleInitBattlePlayerInfo struct {
	PlayerId         *uint64                                        `protobuf:"varint,1,req,name=player_id" json:"player_id,omitempty"`
	PlayerLevel      *uint32                                        `protobuf:"varint,2,req,name=player_level" json:"player_level,omitempty"`
	PlayerName       *string                                        `protobuf:"bytes,3,req,name=player_name" json:"player_name,omitempty"`
	Team             *uint32                                        `protobuf:"varint,4,req,name=team" json:"team,omitempty"`
	RandomCardsInfo  []*S2CBattleInitBattlePlayerInfoBattleCardInfo `protobuf:"bytes,5,rep,name=random_cards_info" json:"random_cards_info,omitempty"`
	XXX_unrecognized []byte                                         `json:"-"`
}

func (m *S2CBattleInitBattlePlayerInfo) Reset()         { *m = S2CBattleInitBattlePlayerInfo{} }
func (m *S2CBattleInitBattlePlayerInfo) String() string { return proto.CompactTextString(m) }
func (*S2CBattleInitBattlePlayerInfo) ProtoMessage()    {}
func (*S2CBattleInitBattlePlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor3, []int{0, 0}
}

func (m *S2CBattleInitBattlePlayerInfo) GetPlayerId() uint64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *S2CBattleInitBattlePlayerInfo) GetPlayerLevel() uint32 {
	if m != nil && m.PlayerLevel != nil {
		return *m.PlayerLevel
	}
	return 0
}

func (m *S2CBattleInitBattlePlayerInfo) GetPlayerName() string {
	if m != nil && m.PlayerName != nil {
		return *m.PlayerName
	}
	return ""
}

func (m *S2CBattleInitBattlePlayerInfo) GetTeam() uint32 {
	if m != nil && m.Team != nil {
		return *m.Team
	}
	return 0
}

func (m *S2CBattleInitBattlePlayerInfo) GetRandomCardsInfo() []*S2CBattleInitBattlePlayerInfoBattleCardInfo {
	if m != nil {
		return m.RandomCardsInfo
	}
	return nil
}

type S2CBattleInitBattlePlayerInfoBattleCardInfo struct {
	CardId           *uint32 `protobuf:"varint,1,req,name=card_id" json:"card_id,omitempty"`
	Level            *uint32 `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	Pos              *uint32 `protobuf:"varint,3,opt,name=pos" json:"pos,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *S2CBattleInitBattlePlayerInfoBattleCardInfo) Reset() {
	*m = S2CBattleInitBattlePlayerInfoBattleCardInfo{}
}
func (m *S2CBattleInitBattlePlayerInfoBattleCardInfo) String() string {
	return proto.CompactTextString(m)
}
func (*S2CBattleInitBattlePlayerInfoBattleCardInfo) ProtoMessage() {}
func (*S2CBattleInitBattlePlayerInfoBattleCardInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor3, []int{0, 0, 0}
}

func (m *S2CBattleInitBattlePlayerInfoBattleCardInfo) GetCardId() uint32 {
	if m != nil && m.CardId != nil {
		return *m.CardId
	}
	return 0
}

func (m *S2CBattleInitBattlePlayerInfoBattleCardInfo) GetLevel() uint32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *S2CBattleInitBattlePlayerInfoBattleCardInfo) GetPos() uint32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func init() {
	proto.RegisterType((*S2CBattleInit)(nil), "protocol.s2c_battle_init")
	proto.RegisterType((*S2CBattleInitBattlePlayerInfo)(nil), "protocol.s2c_battle_init.battle_player_info")
	proto.RegisterType((*S2CBattleInitBattlePlayerInfoBattleCardInfo)(nil), "protocol.s2c_battle_init.battle_player_info.battle_card_info")
}

func init() { proto.RegisterFile("battle_init.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0xd0, 0xbf, 0x4e, 0xeb, 0x30,
	0x14, 0x06, 0x70, 0xe5, 0x4f, 0xef, 0xa5, 0x27, 0x0d, 0x25, 0x86, 0xc1, 0x62, 0x8a, 0x98, 0x32,
	0xa0, 0x44, 0x74, 0x47, 0x48, 0x9d, 0x19, 0x19, 0x10, 0x8b, 0xe5, 0xc6, 0x26, 0xb5, 0x94, 0xd8,
	0x91, 0xe3, 0x46, 0xea, 0xdb, 0xf0, 0x9e, 0x2c, 0x28, 0x76, 0x2c, 0x4a, 0x99, 0x98, 0x92, 0xef,
	0x93, 0x4f, 0xce, 0x2f, 0x86, 0x6c, 0x47, 0x8d, 0x69, 0x39, 0x11, 0x52, 0x98, 0xb2, 0xd7, 0xca,
	0x28, 0x74, 0x61, 0x1f, 0xb5, 0x6a, 0xef, 0x3e, 0x22, 0x58, 0x0f, 0x9b, 0x9a, 0x9c, 0x9c, 0x41,
	0x19, 0x2c, 0x7d, 0x64, 0x38, 0xc8, 0xc3, 0x22, 0x45, 0x97, 0xf0, 0x4f, 0x53, 0xc9, 0x54, 0x87,
	0x43, 0x9b, 0xaf, 0x21, 0x19, 0xb8, 0x1e, 0xb9, 0x26, 0x94, 0x31, 0x8d, 0xa3, 0x3c, 0x2c, 0x96,
	0x53, 0x69, 0x38, 0xed, 0x08, 0xed, 0xd4, 0x41, 0x1a, 0x1c, 0xdb, 0x93, 0x5b, 0x58, 0xf5, 0x2d,
	0x3d, 0x72, 0x3d, 0x10, 0x21, 0xdf, 0x15, 0x5e, 0xe4, 0x51, 0x91, 0x6c, 0xee, 0x4b, 0x2f, 0x28,
	0xcf, 0xb6, 0x97, 0xf3, 0xbb, 0x1b, 0xb2, 0x33, 0xb7, 0x9f, 0x01, 0xa0, 0xdf, 0xf5, 0xe4, 0xf4,
	0xd1, 0x39, 0x63, 0x74, 0xe3, 0xb7, 0x91, 0x96, 0x8f, 0xbc, 0xfd, 0xd6, 0xce, 0xad, 0xa4, 0x1d,
	0x9f, 0xb5, 0x2b, 0x88, 0x27, 0xed, 0xcc, 0x7c, 0x85, 0xcc, 0xfd, 0x20, 0xa9, 0xa9, 0x66, 0x3f,
	0xac, 0x8f, 0x7f, 0xb1, 0xfa, 0x6a, 0xfa, 0x8a, 0xc3, 0x3f, 0xc1, 0xd5, 0x79, 0x87, 0xd6, 0xf0,
	0xdf, 0x05, 0x7f, 0xbf, 0x29, 0x2c, 0x4e, 0xc1, 0x09, 0x44, 0xbd, 0x1a, 0x70, 0x94, 0x07, 0x45,
	0xba, 0x7d, 0x78, 0xab, 0x1a, 0x61, 0xf6, 0x87, 0x5d, 0x59, 0xab, 0xae, 0x62, 0x74, 0x14, 0x6c,
	0xcf, 0xa5, 0x3e, 0x36, 0x54, 0x55, 0xcf, 0xaa, 0x11, 0xf2, 0x85, 0x0f, 0xa6, 0xb2, 0xc6, 0xca,
	0x6d, 0xfa, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xae, 0x91, 0x7e, 0x56, 0xf3, 0x01, 0x00, 0x00,
}
