// Code generated by protoc-gen-go. DO NOT EDIT.
// source: battle_frame_update.proto

package battle

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type S2CBattleFrameUpdate struct {
	FrameId          *uint32                             `protobuf:"varint,1,req,name=frame_id" json:"frame_id,omitempty"`
	BattleActions    []*S2CBattleFrameUpdateBattleAction `protobuf:"bytes,2,rep,name=battle_actions" json:"battle_actions,omitempty"`
	XXX_unrecognized []byte                              `json:"-"`
}

func (m *S2CBattleFrameUpdate) Reset()                    { *m = S2CBattleFrameUpdate{} }
func (m *S2CBattleFrameUpdate) String() string            { return proto.CompactTextString(m) }
func (*S2CBattleFrameUpdate) ProtoMessage()               {}
func (*S2CBattleFrameUpdate) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *S2CBattleFrameUpdate) GetFrameId() uint32 {
	if m != nil && m.FrameId != nil {
		return *m.FrameId
	}
	return 0
}

func (m *S2CBattleFrameUpdate) GetBattleActions() []*S2CBattleFrameUpdateBattleAction {
	if m != nil {
		return m.BattleActions
	}
	return nil
}

type S2CBattleFrameUpdateBattleAction struct {
	PlayerId         *uint64                                     `protobuf:"varint,1,req,name=player_id" json:"player_id,omitempty"`
	Actions          []*S2CBattleFrameUpdateBattleActionActionSt `protobuf:"bytes,2,rep,name=actions" json:"actions,omitempty"`
	XXX_unrecognized []byte                                      `json:"-"`
}

func (m *S2CBattleFrameUpdateBattleAction) Reset()         { *m = S2CBattleFrameUpdateBattleAction{} }
func (m *S2CBattleFrameUpdateBattleAction) String() string { return proto.CompactTextString(m) }
func (*S2CBattleFrameUpdateBattleAction) ProtoMessage()    {}
func (*S2CBattleFrameUpdateBattleAction) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{0, 0}
}

func (m *S2CBattleFrameUpdateBattleAction) GetPlayerId() uint64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *S2CBattleFrameUpdateBattleAction) GetActions() []*S2CBattleFrameUpdateBattleActionActionSt {
	if m != nil {
		return m.Actions
	}
	return nil
}

type S2CBattleFrameUpdateBattleActionActionSt struct {
	ClassId          *uint32 `protobuf:"varint,1,req,name=class_id" json:"class_id,omitempty"`
	Action           *string `protobuf:"bytes,2,req,name=action" json:"action,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *S2CBattleFrameUpdateBattleActionActionSt) Reset() {
	*m = S2CBattleFrameUpdateBattleActionActionSt{}
}
func (m *S2CBattleFrameUpdateBattleActionActionSt) String() string { return proto.CompactTextString(m) }
func (*S2CBattleFrameUpdateBattleActionActionSt) ProtoMessage()    {}
func (*S2CBattleFrameUpdateBattleActionActionSt) Descriptor() ([]byte, []int) {
	return fileDescriptor2, []int{0, 0, 0}
}

func (m *S2CBattleFrameUpdateBattleActionActionSt) GetClassId() uint32 {
	if m != nil && m.ClassId != nil {
		return *m.ClassId
	}
	return 0
}

func (m *S2CBattleFrameUpdateBattleActionActionSt) GetAction() string {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return ""
}

func init() {
	proto.RegisterType((*S2CBattleFrameUpdate)(nil), "protocol.s2c_battle_frame_update")
	proto.RegisterType((*S2CBattleFrameUpdateBattleAction)(nil), "protocol.s2c_battle_frame_update.battle_action")
	proto.RegisterType((*S2CBattleFrameUpdateBattleActionActionSt)(nil), "protocol.s2c_battle_frame_update.battle_action.action_st")
}

func init() { proto.RegisterFile("battle_frame_update.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4c, 0x4a, 0x2c, 0x29,
	0xc9, 0x49, 0x8d, 0x4f, 0x2b, 0x4a, 0xcc, 0x4d, 0x8d, 0x2f, 0x2d, 0x48, 0x49, 0x2c, 0x49, 0xd5,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a, 0x53, 0x98, 0xb8,
	0xc4, 0x8b, 0x8d, 0x92, 0xe3, 0xb1, 0xa8, 0x15, 0x12, 0xe0, 0xe2, 0x80, 0xf0, 0x33, 0x53, 0x24,
	0x18, 0x15, 0x98, 0x34, 0x78, 0x85, 0xdc, 0xb9, 0xf8, 0xa0, 0x0a, 0x13, 0x93, 0x4b, 0x32, 0xf3,
	0xf3, 0x8a, 0x25, 0x98, 0x14, 0x98, 0x35, 0xb8, 0x8d, 0xf4, 0xf5, 0x60, 0x06, 0xea, 0xe1, 0x30,
	0x4c, 0x0f, 0x45, 0x9f, 0xd4, 0x5c, 0x46, 0x2e, 0x5e, 0x14, 0x11, 0x21, 0x41, 0x2e, 0xce, 0x82,
	0x9c, 0xc4, 0xca, 0xd4, 0x22, 0x98, 0x6d, 0x2c, 0x42, 0x5e, 0x5c, 0xec, 0xa8, 0xd6, 0x58, 0x92,
	0x68, 0x8d, 0x1e, 0x84, 0x8a, 0x2f, 0x2e, 0x91, 0xd2, 0xe5, 0xe2, 0x84, 0x73, 0x40, 0x1e, 0x4b,
	0xce, 0x49, 0x2c, 0x2e, 0x46, 0x78, 0x8c, 0x8f, 0x8b, 0x0d, 0x22, 0x2d, 0xc1, 0xa4, 0xc0, 0xa4,
	0xc1, 0xe9, 0x64, 0x18, 0xa5, 0x9f, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab,
	0x9f, 0x92, 0x58, 0x96, 0x99, 0x92, 0x91, 0x9a, 0x57, 0x54, 0x99, 0x9e, 0x98, 0xaf, 0xef, 0x93,
	0x9f, 0x9e, 0x99, 0x17, 0x92, 0x5a, 0x5c, 0xa2, 0x0f, 0x76, 0x8d, 0x3e, 0xc4, 0x4a, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x57, 0xd5, 0x8c, 0x5d, 0x6f, 0x01, 0x00, 0x00,
}
