// Code generated by protoc-gen-go. DO NOT EDIT.
// source: battle_action.proto

/*
Package battle is a generated protocol buffer package.

It is generated from these files:
	battle_action.proto
	battle_end.proto
	battle_frame_update.proto
	battle_init.proto
	battle_ready.proto
	battle_start.proto
	match_cancel.proto
	match_start.proto
	match_update.proto

It has these top-level messages:
	C2SBattleAction
	S2CBattleAction
	C2SBattleEnd
	S2CBattleEnd
	S2CBattleFrameUpdate
	S2CBattleInit
	C2SBattleReady
	S2CBattleReady
	S2CBattleStart
	C2SMatchCancel
	S2CMatchCancel
	C2SMatchStart
	S2CMatchStart
	S2CMatchUpdate
*/
package battle

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type C2SBattleAction struct {
	ClassId          *uint32 `protobuf:"varint,1,req,name=class_id" json:"class_id,omitempty"`
	Action           *string `protobuf:"bytes,2,req,name=action" json:"action,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2SBattleAction) Reset()                    { *m = C2SBattleAction{} }
func (m *C2SBattleAction) String() string            { return proto.CompactTextString(m) }
func (*C2SBattleAction) ProtoMessage()               {}
func (*C2SBattleAction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *C2SBattleAction) GetClassId() uint32 {
	if m != nil && m.ClassId != nil {
		return *m.ClassId
	}
	return 0
}

func (m *C2SBattleAction) GetAction() string {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return ""
}

type S2CBattleAction struct {
	Code             *uint32 `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *S2CBattleAction) Reset()                    { *m = S2CBattleAction{} }
func (m *S2CBattleAction) String() string            { return proto.CompactTextString(m) }
func (*S2CBattleAction) ProtoMessage()               {}
func (*S2CBattleAction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *S2CBattleAction) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*C2SBattleAction)(nil), "protocol.c2s_battle_action")
	proto.RegisterType((*S2CBattleAction)(nil), "protocol.s2c_battle_action")
}

func init() { proto.RegisterFile("battle_action.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x4a, 0x2c, 0x29,
	0xc9, 0x49, 0x8d, 0x4f, 0x4c, 0x2e, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a, 0xa6, 0x5c, 0x82, 0xc9, 0x46, 0xc5, 0xf1, 0x28, 0x8a,
	0x84, 0x04, 0xb8, 0x38, 0x92, 0x73, 0x12, 0x8b, 0x8b, 0xe3, 0x33, 0x53, 0x24, 0x18, 0x15, 0x98,
	0x34, 0x78, 0x85, 0xf8, 0xb8, 0xd8, 0x20, 0x72, 0x12, 0x4c, 0x0a, 0x4c, 0x1a, 0x9c, 0x4a, 0x8a,
	0x5c, 0x82, 0xc5, 0x46, 0xc9, 0x68, 0xda, 0x78, 0xb8, 0x58, 0x92, 0xf3, 0x53, 0x52, 0x21, 0x5a,
	0x9c, 0x0c, 0xa3, 0xf4, 0xd3, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x53,
	0x12, 0xcb, 0x32, 0x53, 0x32, 0x52, 0xf3, 0x8a, 0x2a, 0xd3, 0x13, 0xf3, 0xf5, 0x7d, 0xf2, 0xd3,
	0x33, 0xf3, 0x42, 0x52, 0x8b, 0x4b, 0xf4, 0xc1, 0x0e, 0xd1, 0x87, 0x98, 0x03, 0x08, 0x00, 0x00,
	0xff, 0xff, 0x77, 0xe4, 0xbe, 0x25, 0xac, 0x00, 0x00, 0x00,
}
