// Code generated by protoc-gen-go. DO NOT EDIT.
// source: battle_init.proto

package battle

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type S2CBattleInit struct {
	BattleId         *uint32                          `protobuf:"varint,1,req,name=battle_id" json:"battle_id,omitempty"`
	Random           *uint32                          `protobuf:"varint,2,req,name=random" json:"random,omitempty"`
	ServerAddr       *string                          `protobuf:"bytes,3,req,name=server_addr" json:"server_addr,omitempty"`
	TeamAmount       *uint32                          `protobuf:"varint,4,req,name=team_amount" json:"team_amount,omitempty"`
	PlayersInfo      []*S2CBattleInitBattlePlayerInfo `protobuf:"bytes,5,rep,name=players_info" json:"players_info,omitempty"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (m *S2CBattleInit) Reset()                    { *m = S2CBattleInit{} }
func (m *S2CBattleInit) String() string            { return proto.CompactTextString(m) }
func (*S2CBattleInit) ProtoMessage()               {}
func (*S2CBattleInit) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *S2CBattleInit) GetBattleId() uint32 {
	if m != nil && m.BattleId != nil {
		return *m.BattleId
	}
	return 0
}

func (m *S2CBattleInit) GetRandom() uint32 {
	if m != nil && m.Random != nil {
		return *m.Random
	}
	return 0
}

func (m *S2CBattleInit) GetServerAddr() string {
	if m != nil && m.ServerAddr != nil {
		return *m.ServerAddr
	}
	return ""
}

func (m *S2CBattleInit) GetTeamAmount() uint32 {
	if m != nil && m.TeamAmount != nil {
		return *m.TeamAmount
	}
	return 0
}

func (m *S2CBattleInit) GetPlayersInfo() []*S2CBattleInitBattlePlayerInfo {
	if m != nil {
		return m.PlayersInfo
	}
	return nil
}

type S2CBattleInitBattlePlayerInfo struct {
	PlayerId         *uint64                                        `protobuf:"varint,1,req,name=player_id" json:"player_id,omitempty"`
	PlayerLevel      *uint32                                        `protobuf:"varint,2,req,name=player_level" json:"player_level,omitempty"`
	Team             *uint32                                        `protobuf:"varint,3,req,name=team" json:"team,omitempty"`
	RandomCardsInfo  []*S2CBattleInitBattlePlayerInfoBattleCardInfo `protobuf:"bytes,4,rep,name=random_cards_info" json:"random_cards_info,omitempty"`
	XXX_unrecognized []byte                                         `json:"-"`
}

func (m *S2CBattleInitBattlePlayerInfo) Reset()         { *m = S2CBattleInitBattlePlayerInfo{} }
func (m *S2CBattleInitBattlePlayerInfo) String() string { return proto.CompactTextString(m) }
func (*S2CBattleInitBattlePlayerInfo) ProtoMessage()    {}
func (*S2CBattleInitBattlePlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor3, []int{0, 0}
}

func (m *S2CBattleInitBattlePlayerInfo) GetPlayerId() uint64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

func (m *S2CBattleInitBattlePlayerInfo) GetPlayerLevel() uint32 {
	if m != nil && m.PlayerLevel != nil {
		return *m.PlayerLevel
	}
	return 0
}

func (m *S2CBattleInitBattlePlayerInfo) GetTeam() uint32 {
	if m != nil && m.Team != nil {
		return *m.Team
	}
	return 0
}

func (m *S2CBattleInitBattlePlayerInfo) GetRandomCardsInfo() []*S2CBattleInitBattlePlayerInfoBattleCardInfo {
	if m != nil {
		return m.RandomCardsInfo
	}
	return nil
}

type S2CBattleInitBattlePlayerInfoBattleCardInfo struct {
	CardId           *uint32 `protobuf:"varint,1,req,name=card_id" json:"card_id,omitempty"`
	Level            *uint32 `protobuf:"varint,2,req,name=level" json:"level,omitempty"`
	Pos              *uint32 `protobuf:"varint,3,opt,name=pos" json:"pos,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *S2CBattleInitBattlePlayerInfoBattleCardInfo) Reset() {
	*m = S2CBattleInitBattlePlayerInfoBattleCardInfo{}
}
func (m *S2CBattleInitBattlePlayerInfoBattleCardInfo) String() string {
	return proto.CompactTextString(m)
}
func (*S2CBattleInitBattlePlayerInfoBattleCardInfo) ProtoMessage() {}
func (*S2CBattleInitBattlePlayerInfoBattleCardInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor3, []int{0, 0, 0}
}

func (m *S2CBattleInitBattlePlayerInfoBattleCardInfo) GetCardId() uint32 {
	if m != nil && m.CardId != nil {
		return *m.CardId
	}
	return 0
}

func (m *S2CBattleInitBattlePlayerInfoBattleCardInfo) GetLevel() uint32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *S2CBattleInitBattlePlayerInfoBattleCardInfo) GetPos() uint32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func init() {
	proto.RegisterType((*S2CBattleInit)(nil), "protocol.s2c_battle_init")
	proto.RegisterType((*S2CBattleInitBattlePlayerInfo)(nil), "protocol.s2c_battle_init.battle_player_info")
	proto.RegisterType((*S2CBattleInitBattlePlayerInfoBattleCardInfo)(nil), "protocol.s2c_battle_init.battle_player_info.battle_card_info")
}

func init() { proto.RegisterFile("battle_init.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0xd0, 0x4f, 0x4f, 0x83, 0x30,
	0x18, 0x06, 0xf0, 0xf0, 0x67, 0xea, 0x5e, 0x86, 0x93, 0xea, 0xa1, 0xf1, 0x44, 0x3c, 0x71, 0x30,
	0x10, 0x77, 0x37, 0x26, 0x3b, 0x7b, 0xf4, 0x60, 0xbc, 0x34, 0x1d, 0xad, 0xac, 0x09, 0xb4, 0xa4,
	0x74, 0x24, 0xfb, 0x0c, 0x7e, 0x4f, 0x3f, 0x87, 0xa1, 0xa5, 0xc9, 0x32, 0x4f, 0x3b, 0xc1, 0xf3,
	0xa4, 0x2f, 0xef, 0x8f, 0x42, 0xb6, 0xa3, 0xc6, 0xb4, 0x9c, 0x08, 0x29, 0x4c, 0xd9, 0x6b, 0x65,
	0x14, 0xba, 0xb1, 0x8f, 0x5a, 0xb5, 0x4f, 0x3f, 0x11, 0xac, 0x87, 0x4d, 0x4d, 0x4e, 0xce, 0xa0,
	0x0c, 0x96, 0x3e, 0x32, 0x1c, 0xe4, 0x61, 0x91, 0xa2, 0x5b, 0xb8, 0xd2, 0x54, 0x32, 0xd5, 0xe1,
	0xd0, 0xe6, 0x7b, 0x48, 0x06, 0xae, 0x47, 0xae, 0x09, 0x65, 0x4c, 0xe3, 0x28, 0x0f, 0x8b, 0xe5,
	0x54, 0x1a, 0x4e, 0x3b, 0x42, 0x3b, 0x75, 0x90, 0x06, 0xc7, 0xf6, 0xe4, 0x16, 0x56, 0x7d, 0x4b,
	0x8f, 0x5c, 0x0f, 0x44, 0xc8, 0x6f, 0x85, 0x17, 0x79, 0x54, 0x24, 0x9b, 0xe7, 0xd2, 0x0b, 0xca,
	0xb3, 0xed, 0xe5, 0xfc, 0xee, 0x86, 0xec, 0xcc, 0xe3, 0x6f, 0x00, 0xe8, 0x7f, 0x3d, 0x39, 0x7d,
	0x74, 0xce, 0x18, 0x3d, 0xf8, 0x6d, 0xa4, 0xe5, 0x23, 0x6f, 0x67, 0xed, 0x0a, 0xe2, 0x09, 0x66,
	0x99, 0x29, 0xfa, 0x84, 0xcc, 0xfd, 0x0b, 0xa9, 0xa9, 0x66, 0x33, 0x2b, 0xb6, 0xac, 0xd7, 0x4b,
	0x58, 0xbe, 0x9a, 0xbe, 0xe2, 0x9c, 0x6f, 0x70, 0x77, 0xde, 0xa1, 0x35, 0x5c, 0xbb, 0xe0, 0xaf,
	0x32, 0x85, 0xc5, 0xa9, 0x2d, 0x81, 0xa8, 0x57, 0x03, 0x8e, 0xf2, 0xa0, 0x48, 0xb7, 0x2f, 0x5f,
	0x55, 0x23, 0xcc, 0xfe, 0xb0, 0x2b, 0x6b, 0xd5, 0x55, 0x8c, 0x8e, 0x82, 0xed, 0xb9, 0xd4, 0xc7,
	0x86, 0xaa, 0xea, 0x5d, 0x35, 0x42, 0x7e, 0xf0, 0xc1, 0x54, 0xd6, 0x58, 0xb9, 0x4d, 0x7f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x90, 0x1f, 0x94, 0x1b, 0xde, 0x01, 0x00, 0x00,
}
