//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/cmd.proto
namespace proto
{
    [global::ProtoBuf.ProtoContract(Name=@"cmd")]
    public enum cmd
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"HEARTBEAT", Value=1)]
      HEARTBEAT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ECHO", Value=2)]
      ECHO = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGOUT", Value=3)]
      LOGOUT = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_CHALLENGE", Value=100)]
      LOGIN_CHALLENGE = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_EXCHANGEKEY", Value=101)]
      LOGIN_EXCHANGEKEY = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_HANDSHAKE", Value=102)]
      LOGIN_HANDSHAKE = 102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN", Value=103)]
      LOGIN = 103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOGIN_LAUNCH", Value=104)]
      LOGIN_LAUNCH = 104
    }
  
}