//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/exchangekey.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_exchangekey")]
  public partial class c2s_exchangekey : global::ProtoBuf.IExtensible
  {
    public c2s_exchangekey() {}
    
    private string _clientkey;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"clientkey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string clientkey
    {
      get { return _clientkey; }
      set { _clientkey = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_exchangekey")]
  public partial class s2c_exchangekey : global::ProtoBuf.IExtensible
  {
    public s2c_exchangekey() {}
    
    private int _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int code
    {
      get { return _code; }
      set { _code = value; }
    }
    private string _serverkey = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"serverkey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string serverkey
    {
      get { return _serverkey; }
      set { _serverkey = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}