//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/login.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c2s_login")]
  public partial class c2s_login : global::ProtoBuf.IExtensible
  {
    public c2s_login() {}
    
    private string _token;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"s2c_login")]
  public partial class s2c_login : global::ProtoBuf.IExtensible
  {
    public s2c_login() {}
    
    private int _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int code
    {
      get { return _code; }
      set { _code = value; }
    }
    private s2c_login.result _info = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public s2c_login.result info
    {
      get { return _info; }
      set { _info = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"result")]
  public partial class result : global::ProtoBuf.IExtensible
  {
    public result() {}
    
    private string _subid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"subid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string subid
    {
      get { return _subid; }
      set { _subid = value; }
    }
    private string _server_addr;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"server_addr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string server_addr
    {
      get { return _server_addr; }
      set { _server_addr = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}