//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/test/test.proto
namespace proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"test")]
  public partial class test : global::ProtoBuf.IExtensible
  {
    public test() {}
    
    private string _s;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"s", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string s
    {
      get { return _s; }
      set { _s = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}