// Code generated by protoc-gen-go. DO NOT EDIT.
// source: card.proto

/*
Package card is a generated protocol buffer package.

It is generated from these files:
	card.proto
	card_deck.proto
	change_card_deck.proto
	change_deck.proto
	check_card.proto
	gm_get_card.proto
	load_card_decks.proto
	load_cards.proto
	up_card_level.proto
	update_cards.proto

It has these top-level messages:
	Card
	CardDeck
	ChangeInfo
	C2SChangeCardDeck
	S2CChangeCardDeck
	C2SChange_Deck
	S2CChangeDeck
	C2SCheckCard
	S2CCheckCard
	C2SGmGetCard
	S2CGmGetCard
	C2SLoadCardDecks
	S2CLoadCardDecks
	C2SLoadCards
	S2CLoadCards
	C2SUpCardLevel
	S2CUpCardLevel
	S2CUpdateCards
*/
package card

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Card struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Level            *uint32 `protobuf:"varint,2,opt,name=level" json:"level,omitempty"`
	Amount           *uint32 `protobuf:"varint,3,opt,name=amount" json:"amount,omitempty"`
	State            *uint32 `protobuf:"varint,4,opt,name=state" json:"state,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Card) Reset()                    { *m = Card{} }
func (m *Card) String() string            { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()               {}
func (*Card) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Card) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Card) GetLevel() uint32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *Card) GetAmount() uint32 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

func (m *Card) GetState() uint32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func init() {
	proto.RegisterType((*Card)(nil), "protocol.card")
}

func init() { proto.RegisterFile("card.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4e, 0x2c, 0x4a,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a, 0x0e, 0x5c,
	0x2c, 0x20, 0x71, 0x21, 0x2e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x26, 0x0d, 0x5e, 0x21,
	0x5e, 0x2e, 0xd6, 0x9c, 0xd4, 0xb2, 0xd4, 0x1c, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x5e, 0x21, 0x3e,
	0x2e, 0xb6, 0xc4, 0xdc, 0xfc, 0xd2, 0xbc, 0x12, 0x09, 0x66, 0x30, 0x9f, 0x97, 0x8b, 0xb5, 0xb8,
	0x24, 0xb1, 0x24, 0x55, 0x82, 0x05, 0xc4, 0x75, 0xd2, 0x8f, 0xd2, 0x4d, 0xcf, 0x2c, 0xc9, 0x28,
	0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0x49, 0x2c, 0xcb, 0x4c, 0xc9, 0x48, 0xcd, 0x2b, 0xaa,
	0x4c, 0x4f, 0xcc, 0xd7, 0xf7, 0xc9, 0x4f, 0xcf, 0xcc, 0x0b, 0x49, 0x2d, 0x2e, 0xd1, 0x07, 0x5b,
	0xa8, 0x0f, 0xb2, 0x0a, 0x10, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x62, 0xd1, 0x6f, 0x89, 0x00, 0x00,
	0x00,
}
