// Code generated by protoc-gen-go. DO NOT EDIT.
// source: change_card_deck.proto

package card

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ChangeInfo struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Pos              *uint32 `protobuf:"varint,2,req,name=pos" json:"pos,omitempty"`
	CardDeckIndex    *uint32 `protobuf:"varint,3,opt,name=card_deck_index" json:"card_deck_index,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ChangeInfo) Reset()                    { *m = ChangeInfo{} }
func (m *ChangeInfo) String() string            { return proto.CompactTextString(m) }
func (*ChangeInfo) ProtoMessage()               {}
func (*ChangeInfo) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *ChangeInfo) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *ChangeInfo) GetPos() uint32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func (m *ChangeInfo) GetCardDeckIndex() uint32 {
	if m != nil && m.CardDeckIndex != nil {
		return *m.CardDeckIndex
	}
	return 0
}

type C2SChangeCardDeck struct {
	Change           *ChangeInfo `protobuf:"bytes,1,req,name=change" json:"change,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *C2SChangeCardDeck) Reset()                    { *m = C2SChangeCardDeck{} }
func (m *C2SChangeCardDeck) String() string            { return proto.CompactTextString(m) }
func (*C2SChangeCardDeck) ProtoMessage()               {}
func (*C2SChangeCardDeck) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *C2SChangeCardDeck) GetChange() *ChangeInfo {
	if m != nil {
		return m.Change
	}
	return nil
}

type S2CChangeCardDeck struct {
	Code             *int32      `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Change           *ChangeInfo `protobuf:"bytes,2,opt,name=change" json:"change,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *S2CChangeCardDeck) Reset()                    { *m = S2CChangeCardDeck{} }
func (m *S2CChangeCardDeck) String() string            { return proto.CompactTextString(m) }
func (*S2CChangeCardDeck) ProtoMessage()               {}
func (*S2CChangeCardDeck) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *S2CChangeCardDeck) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *S2CChangeCardDeck) GetChange() *ChangeInfo {
	if m != nil {
		return m.Change
	}
	return nil
}

func init() {
	proto.RegisterType((*ChangeInfo)(nil), "protocol.change_info")
	proto.RegisterType((*C2SChangeCardDeck)(nil), "protocol.c2s_change_card_deck")
	proto.RegisterType((*S2CChangeCardDeck)(nil), "protocol.s2c_change_card_deck")
}

func init() { proto.RegisterFile("change_card_deck.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8d, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x40, 0x69, 0xaa, 0x22, 0x53, 0x8b, 0x10, 0xaa, 0xf6, 0x58, 0x0a, 0x42, 0x2f, 0x26, 0xd0,
	0xbb, 0x08, 0x5e, 0xf5, 0xe8, 0xc9, 0x4b, 0x88, 0x93, 0x98, 0x06, 0x35, 0x53, 0x9a, 0x2a, 0xfa,
	0xf7, 0x62, 0xea, 0x2e, 0x65, 0x97, 0x3d, 0x0d, 0x33, 0xcc, 0x7b, 0x0f, 0x2e, 0x71, 0xd0, 0xc1,
	0x59, 0x85, 0x7a, 0x32, 0xca, 0x58, 0x7c, 0x13, 0xe3, 0x44, 0x33, 0xf1, 0xd3, 0x34, 0x90, 0xde,
	0xdb, 0x3b, 0x28, 0xfe, 0x7f, 0x7c, 0x78, 0x25, 0x0e, 0xc0, 0xbc, 0xa9, 0xb3, 0x86, 0x75, 0x25,
	0x2f, 0x20, 0x1f, 0x29, 0xd6, 0x2c, 0x2d, 0x57, 0x70, 0xbe, 0x95, 0x28, 0x1f, 0x8c, 0xfd, 0xae,
	0xf3, 0x26, 0xeb, 0xca, 0xf6, 0x16, 0x2a, 0xec, 0xa3, 0xda, 0x0d, 0xf1, 0x6b, 0x38, 0x59, 0x6e,
	0xc9, 0x56, 0xf4, 0x17, 0x62, 0xd3, 0x14, 0xab, 0x60, 0xfb, 0x00, 0x55, 0xec, 0x71, 0x1f, 0x3f,
	0x83, 0x23, 0x24, 0xb3, 0xc0, 0xc7, 0x2b, 0x19, 0x6b, 0xb2, 0x83, 0xb2, 0x7b, 0xf9, 0x7c, 0xe3,
	0xfc, 0x3c, 0x7c, 0xbe, 0x08, 0xa4, 0x0f, 0x69, 0xf4, 0x97, 0x37, 0x83, 0x0d, 0xd3, 0x8f, 0xd3,
	0x24, 0x1f, 0xc9, 0xf9, 0xf0, 0x64, 0xe3, 0x2c, 0x13, 0x2a, 0xff, 0x52, 0xbf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x25, 0x67, 0x1e, 0x8f, 0x20, 0x01, 0x00, 0x00,
}
