// Code generated by protoc-gen-go. DO NOT EDIT.
// source: up_card_level.proto

package card

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type C2SUpCardLevel struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	UpLevel          *uint32 `protobuf:"varint,2,opt,name=up_level,def=1" json:"up_level,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *C2SUpCardLevel) Reset()                    { *m = C2SUpCardLevel{} }
func (m *C2SUpCardLevel) String() string            { return proto.CompactTextString(m) }
func (*C2SUpCardLevel) ProtoMessage()               {}
func (*C2SUpCardLevel) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{0} }

const Default_C2SUpCardLevel_UpLevel uint32 = 1

func (m *C2SUpCardLevel) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *C2SUpCardLevel) GetUpLevel() uint32 {
	if m != nil && m.UpLevel != nil {
		return *m.UpLevel
	}
	return Default_C2SUpCardLevel_UpLevel
}

type S2CUpCardLevel struct {
	Code             *int32                      `protobuf:"varint,1,req,name=code" json:"code,omitempty"`
	Info             *S2CUpCardLevelCardLvUpInfo `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *S2CUpCardLevel) Reset()                    { *m = S2CUpCardLevel{} }
func (m *S2CUpCardLevel) String() string            { return proto.CompactTextString(m) }
func (*S2CUpCardLevel) ProtoMessage()               {}
func (*S2CUpCardLevel) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{1} }

func (m *S2CUpCardLevel) GetCode() int32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *S2CUpCardLevel) GetInfo() *S2CUpCardLevelCardLvUpInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type S2CUpCardLevelCardLvUpInfo struct {
	Id               *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	OrgLevel         *uint32 `protobuf:"varint,2,req,name=org_level" json:"org_level,omitempty"`
	UpLevel          *uint32 `protobuf:"varint,3,opt,name=up_level,def=1" json:"up_level,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *S2CUpCardLevelCardLvUpInfo) Reset()                    { *m = S2CUpCardLevelCardLvUpInfo{} }
func (m *S2CUpCardLevelCardLvUpInfo) String() string            { return proto.CompactTextString(m) }
func (*S2CUpCardLevelCardLvUpInfo) ProtoMessage()               {}
func (*S2CUpCardLevelCardLvUpInfo) Descriptor() ([]byte, []int) { return fileDescriptor8, []int{1, 0} }

const Default_S2CUpCardLevelCardLvUpInfo_UpLevel uint32 = 1

func (m *S2CUpCardLevelCardLvUpInfo) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *S2CUpCardLevelCardLvUpInfo) GetOrgLevel() uint32 {
	if m != nil && m.OrgLevel != nil {
		return *m.OrgLevel
	}
	return 0
}

func (m *S2CUpCardLevelCardLvUpInfo) GetUpLevel() uint32 {
	if m != nil && m.UpLevel != nil {
		return *m.UpLevel
	}
	return Default_S2CUpCardLevelCardLvUpInfo_UpLevel
}

func init() {
	proto.RegisterType((*C2SUpCardLevel)(nil), "protocol.c2s_up_card_level")
	proto.RegisterType((*S2CUpCardLevel)(nil), "protocol.s2c_up_card_level")
	proto.RegisterType((*S2CUpCardLevelCardLvUpInfo)(nil), "protocol.s2c_up_card_level.card_lv_up_info")
}

func init() { proto.RegisterFile("up_card_level.proto", fileDescriptor8) }

var fileDescriptor8 = []byte{
	// 204 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x2d, 0x88, 0x4f,
	0x4e, 0x2c, 0x4a, 0x89, 0xcf, 0x49, 0x2d, 0x4b, 0xcd, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x00, 0x53, 0xc9, 0xf9, 0x39, 0x4a, 0x26, 0x5c, 0x82, 0xc9, 0x46, 0xc5, 0xf1, 0x28, 0x8a,
	0x84, 0xb8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x98, 0x34, 0x78, 0x85, 0x84, 0xb9, 0x38,
	0x4a, 0x0b, 0x20, 0xe2, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xbc, 0x56, 0x8c, 0x86, 0x4a, 0x8b, 0x19,
	0xb9, 0x04, 0x8b, 0x8d, 0x92, 0xd1, 0xb4, 0xf1, 0x70, 0xb1, 0x24, 0xe7, 0xa7, 0xa4, 0x82, 0x35,
	0xb2, 0x0a, 0x59, 0x72, 0xb1, 0x64, 0xe6, 0xa5, 0xe5, 0x83, 0x35, 0x71, 0x1b, 0x69, 0xeb, 0xc1,
	0xac, 0xd4, 0xc3, 0xd0, 0xa8, 0x07, 0x61, 0x96, 0x81, 0x44, 0x41, 0x5a, 0xa4, 0x5c, 0xb9, 0xf8,
	0xd1, 0x84, 0x50, 0x9c, 0x24, 0xc8, 0xc5, 0x99, 0x5f, 0x94, 0x0e, 0x77, 0x13, 0xba, 0x2b, 0x99,
	0xa1, 0xae, 0x74, 0xd2, 0x8f, 0xd2, 0x4d, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf,
	0xd5, 0x4f, 0x49, 0x2c, 0xcb, 0x4c, 0xc9, 0x48, 0xcd, 0x2b, 0xaa, 0x4c, 0x4f, 0xcc, 0xd7, 0xf7,
	0xc9, 0x4f, 0xcf, 0xcc, 0x0b, 0x49, 0x2d, 0x2e, 0xd1, 0x07, 0xbb, 0x4b, 0x1f, 0x64, 0x1f, 0x20,
	0x00, 0x00, 0xff, 0xff, 0x2d, 0x5a, 0xd6, 0xf0, 0x2c, 0x01, 0x00, 0x00,
}
